import { ArrowLeft, ExternalLink } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { useEditorialMarket } from '@/hooks/useEditorialMarket';
import { editorialCardUrl, editorialSetUrl } from '@/lib/editorialMarketLinks';
export default function EditorialMarketArticle() {
  const { slug } = useParams<{ slug: string }>(); const { data, loading } = useEditorialMarket();
  const article = data && Object.values(data.articles).find((item) => item.slug === slug); const category = data && Object.keys(data.articles).find((key) => data.articles[key].slug === slug); const movers = data?.movers.filter((item) => item.category === category) ?? [];
  if (loading) return <main className="mx-auto max-w-3xl px-4 py-12 text-muted-foreground">Loading article…</main>;
  if (!article) return <main className="mx-auto max-w-3xl px-4 py-12"><p>Article not found.</p><Link href="/market-articles" className="mt-4 inline-block text-primary underline">Back to articles</Link></main>;
  return <div className="min-h-screen bg-background text-foreground"><header className="border-b-2 border-border bg-card"><div className="mx-auto max-w-5xl px-4 py-5 sm:px-8"><Link href="/market-articles" className="inline-flex items-center gap-2 font-mono text-xs uppercase text-primary hover:underline"><ArrowLeft className="h-4 w-4" /> All deep dives</Link></div></header><main className="mx-auto max-w-5xl px-4 py-10 sm:px-8"><article className="max-w-3xl"><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-primary">{article.kicker} · {data?.snapshot.label}</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">{article.title}</h1><p className="mt-5 text-xl leading-relaxed text-muted-foreground">{article.dek}</p><div className="mt-10 space-y-6 text-[17px] leading-8">{article.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></article><section className="mt-16 border-t-2 border-primary pt-8"><p className="font-mono text-xs font-bold uppercase tracking-wider text-primary">Linked evidence</p><h2 className="mt-2 text-2xl font-bold">Cards in {category}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{movers.map((mover) => <div key={mover.id} className="border-2 border-border bg-card p-4"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{mover.name}</h3><p className="text-sm text-muted-foreground">{mover.setName} · {mover.printing}</p></div><span className={mover.changePercent >= 0 ? 'font-bold text-emerald-600' : 'font-bold text-rose-600'}>{mover.changePercent >= 0 ? '+' : ''}{mover.changePercent}%</span></div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{mover.thesis}</p><div className="mt-4 flex gap-4 font-mono text-[10px] font-bold uppercase"><a href={editorialCardUrl(mover.name)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary hover:underline">Card <ExternalLink className="h-3 w-3" /></a><a href={editorialSetUrl(mover.setName)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary hover:underline">Set <ExternalLink className="h-3 w-3" /></a></div></div>)}</div></section></main></div>;
}
