import { ArrowLeft, ArrowRight, ExternalLink, Layers3, ShieldAlert, Sparkles, TrendingUp } from 'lucide-react';
import { Link } from 'wouter';
import { InternalPageNav } from '@/components/InternalPageNav';
import { manusMoverBaskets, manusMoverDashboards, manusMoverReport } from '@/data/marketMoverManusReport';

const deskIcons = [<TrendingUp className="h-5 w-5" />, <Sparkles className="h-5 w-5" />, <ShieldAlert className="h-5 w-5" />, <Layers3 className="h-5 w-5" />];

export default function MarketMoverReportArticle() {
  return <div className="min-h-screen bg-background text-foreground">
    <InternalPageNav active="/movers" />
    <header className="border-b-2 border-border bg-card">
      <div className="mx-auto max-w-5xl px-4 py-8 sm:px-8 sm:py-12">
        <Link href="/movers" className="inline-flex items-center gap-2 font-mono text-xs font-black uppercase tracking-widest text-primary hover:underline"><ArrowLeft className="h-4 w-4" /> Back to market movers</Link>
        <p className="mt-10 font-mono text-xs font-black uppercase tracking-[0.2em] text-primary">Field note · {manusMoverReport.published}</p>
        <h1 className="mt-3 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">{manusMoverReport.title}</h1>
        <p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{manusMoverReport.dek}</p>
        <div className="mt-6 flex flex-wrap gap-3 font-mono text-xs font-bold uppercase tracking-wider text-muted-foreground"><span>Imported Manus export</span><span>Signal-first</span><span>Updated {manusMoverReport.updated}</span></div>
      </div>
    </header>
    <main className="mx-auto max-w-5xl space-y-10 px-4 py-8 sm:px-8 sm:py-12">
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{manusMoverReport.metrics.map((metric) => <div key={metric.label} className="border-2 border-border bg-card p-4"><p className="text-3xl font-black text-primary">{metric.value}</p><p className="mt-2 font-mono text-[10px] font-bold uppercase leading-relaxed tracking-wider text-muted-foreground">{metric.label}</p></div>)}</section>
      <article className="space-y-6 border-2 border-border bg-card p-6 sm:p-10"><div className="flex items-center gap-2 font-mono text-xs font-black uppercase tracking-widest text-primary"><Sparkles className="h-4 w-4" /> Editorial read</div><p className="text-lg leading-8">The supplied export is most useful when it refuses to call every percentage move an opportunity. It separates the cleanest headline names from lower-cost Commander pieces, then isolates the moves that look more like inventory shocks. That distinction is the difference between a watchlist and a chase list.</p><p className="text-base leading-8 text-muted-foreground">The strongest confirmed narratives combine visible demand with a reason for the demand to persist: premium fast mana, Reserved List scarcity, or a broadly playable Commander staple. The budget desk is different. Carth the Lion, Deepglow Skate, Azor, Raffine, and Wellwisher are useful because they express an archetype or treatment thesis without requiring the same capital as a four-figure staple.</p><p className="text-base leading-8 text-muted-foreground">The defensive desk is equally important. Vronos, premium Secret Lair basics, Unesh, and Sphinx Ambassador may all be interesting records of market activity, but the report flags thin supply, bulk orders, or already-extended prices. Those are reasons to wait for fresh listings and repeat transactions—not reasons to extrapolate a vertical chart.</p><p className="text-base leading-8 text-muted-foreground">Finally, the supply clock turns product knowledge into a market signal. Doom Prevails singles, Warhammer 40K reprints, and Mystery Booster Commander Edition targets should be watched around release and legality dates. In these cases, the key question is how access changes, not whether a card had a dramatic move yesterday.</p></article>
      <section><div className="flex flex-wrap items-end justify-between gap-3 border-b-2 border-border pb-4"><div><p className="font-mono text-xs font-black uppercase tracking-widest text-primary">Choose a desk</p><h2 className="mt-2 text-3xl font-black">Four separate mover dashboards</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Each dashboard keeps its own evidence standard and risk posture.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{manusMoverDashboards.map((dashboard, index) => <Link key={dashboard.slug} href={`/movers/${dashboard.slug}`} className="group border-2 border-border bg-card p-5 hover:border-primary"><div className="flex items-center justify-between"><span className="text-primary">{deskIcons[index]}</span><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div><h3 className="mt-5 text-xl font-black">{dashboard.label}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{dashboard.description}</p><p className="mt-4 font-mono text-[10px] font-black uppercase tracking-wider text-primary">Open dashboard →</p></Link>)}</div></section>
      <section><div className="border-b-2 border-border pb-4"><p className="font-mono text-xs font-black uppercase tracking-widest text-primary">Thematic baskets</p><h2 className="mt-2 text-2xl font-black">Keep the catalyst clusters together</h2></div><div className="mt-5 grid gap-4">{manusMoverBaskets.map((basket) => <div key={basket.label} className="border-2 border-border bg-card p-5"><h3 className="font-bold">{basket.label}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{basket.cards}</p></div>)}</div></section>
      <section className="border-2 border-amber-600/40 bg-amber-500/5 p-5 sm:p-6"><p className="font-mono text-xs font-black uppercase tracking-widest text-amber-700">Method note</p><p className="mt-3 text-sm leading-7 text-muted-foreground">This post incorporates the attached HTML export as editorial market intelligence. It does not replace live pricing. Confirm current listings, sales depth, set identity, treatment, reprint status, and Commander legality before making a purchase decision.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/movers" className="border-2 border-primary bg-primary px-3 py-2 font-mono text-xs font-black uppercase text-primary-foreground hover:opacity-90">Live mover feed</Link><a href="https://scryfall.com" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 border-2 border-border bg-background px-3 py-2 font-mono text-xs font-black uppercase hover:border-primary">Verify on Scryfall <ExternalLink className="h-3 w-3" /></a></div></section>
    </main>
  </div>;
}
